### DISCUSSION TITLE
Example 15 Style dpad - not showing correct on mobile phone

### DISCUSSION THREAD

**Discussion by jerxjac** [Nerwyn/universal-remote-card#105] [Q&A] [answered]
Hi I really like the  Example 15  Style dpad ,
But It look weird on my android phone.
![Screenshot_20240710_144512_Home Assistant](https://github.com/Nerwyn/android-tv-card/assets/38360412/d32555fd-0b17-481a-97ec-f4887cc33d55)

Somebody any idea how to fix this?

**Comment by Nerwyn** [comment, marked as answer]
Did you include the row styles? You have to change the row numbers to match the IDs of the row elements, which can be found using browser developer tools or just guessing until the styles apply correctly. it looks like yours start on the second row so it should be:

```yaml
row_styles:
  row-2:
    justify-content: center
  row-3:
    justify-content: center
  row-4:
    justify-content: center
```
