### DISCUSSION TITLE
Launching and app by package name opens google play store

### DISCUSSION THREAD

**Discussion by mk89pwnz** [Nerwyn/universal-remote-card#119] [Q&A]
Any way to make it open rather then open the play store link, I have and IPTV box with biult in telia app that always auto launches, but it's available in play store and updates via it, with this custom action button opens google play store but not the app.

```yaml
telia:
    icon: mdi:television-box
    style:
      '--icon-color': >-
        {% if is_state_attr('remote.android_tv','current_activity',
        'lt.telia.tv') %} blueviolet {% endif %}
    tap_action:
      action: source
      source: lt.telia.tv
```

**Comment by Nerwyn** [comment]
This issue also exists with the Max app, but as far as I can tell it's an issue with the apps themselves.

Related issue #77

**Reply by mk89pwnz** [reply]
Thanks, first it was working ok with remote.send_command, but after some time it stopped working, there is no deeplink in the app and as it's just android tv box I believe I can't just change source to app or at least it's not working for me with this:
```yaml
tap_action:
  action: call-service
  service: media_player.select_source
  target:
      device_id: 48edc0cada425e7fec7eae408d446ef6
  data:
    source: lt.telia.tv
```

I used button remapper and my remote have a dedicated button for this app it's BUTTON_14 but it stopped working after android tv update or maybe your card was updated don't rly know as when it stopped working didn't had time to check only now decided to finally fix it. If remote has the button android tv command should still work? or do I need to use remap apps and set the same button to start the app I want? As this is not working anymore:

```yaml
  telia:
    icon: mdi:television-box
    style:
      color: >-
        {% if is_state_attr('remote.telia_tv','current_activity', 'lt.telia.tv')
        %} blueviolet {% endif %}
    tap_action:
      service: remote.send_command
      data:
        command: BUTTON_14
      target:
        entity_id: remote.android_tv
```

**Comment by mk89pwnz** [comment]
Manage to sort this out but only when I got my new ccgtv 4k, using adb, so if anyone iptv tv box with android still has not locked adb you can just use:
```yaml
action: media_player.select_source
target:
  entity_id: media_player.android_tv_190_000_0_188
data:
  source: lt.telia.tv
```
