### DISCUSSION TITLE
Integrate NowTV and Settings

### DISCUSSION THREAD

**Discussion by Marcoluca56** [Nerwyn/universal-remote-card#123] [Q&A]
Hello everyone, first of all thanks and compliments for everything. I would like to implement NowTV, how can I do it?
I also have a sony tv how can I also implement the button to enter the tv settings?
Thank you very much everyone

**Comment by Nerwyn** [comment]
You need to find its deep link using the [deep linking guide](https://community.home-assistant.io/t/android-tv-remote-app-links-deep-linking-guide/567921) and an SVG icon, and then use a tool like [this SVG path editor](https://yqnn.github.io/svg-path-editor/) to make it work with this project.

Does your TV run Android TV or is it an older version that uses Sony software? If the settings button doesn't work it may be proprietary.

**Reply by Marcoluca56** [reply]
where do I go to add the rule for the NOW program? What is the path and how do I do it directly from HomeAssistant? Thanks

**Reply by Nerwyn** [reply]
Have you read the README? It talks about creating custom actions and icons there.

Using the actions dev tool you can fire the `remote.turn_on` command to test it.

```yaml
action: remote.turn_on
data:
  activity: NowTVDeepLinkGoesHere
target:
  entity_id: remote.lounge_google_tv
```

You can define a custom action with the same YAML as it's tap action as described in the README.

Version 4 is almost ready for release and you can use it's beta if you want to do all of this through a configuration UI.

**Reply by Marcoluca56** [reply]
Thanks for your reply.
I test it but without success... i tried with:

```yaml
type: custom:android-tv-card
remote_id: remote.sony_xr_42a90k
keyboard_id: media_player.tv_cucina
slider_id: media_player.tv_cucina_homekit_television

rows:
  - - test
custom_actions:
  test:
    icon: mdi:netflix
    tap_action:
      action: source
      source: nowtv-it://
```

but nothing happens. Where am I going wrong?
I looked at the deeplink schemes and these are them:

```  
 <string name="deeplink_host_http">watch.nowtv.com</string>

    <string name="deeplink_scheme_atlas">atlas</string>

    <string name="deeplink_scheme_nowtv">nowtv</string>

    <string name="deeplink_scheme_nowtv_de">sky-ticket</string>

    <string name="deeplink_scheme_nowtv_es">nowtv-es</string>

    <string name="deeplink_scheme_nowtv_ie">nowtv</string>

    <string name="deeplink_scheme_nowtv_it">nowtv-it</string>
```

Thanks
