### DISCUSSION TITLE
LG OS integration

### DISCUSSION THREAD

**Discussion by mk89pwnz** [Nerwyn/universal-remote-card#130] [Q&A]
I tried new version today but if I set my media player to LG one volume buttons do not work I get Action webos.button not found, and when I define the buttons in custom actions it works. Is this by design or smth is wrong with my config?

**Comment by Nerwyn** [comment]
It looks like I misspelled the action name for LG webOS and used the wrong data key [as defined here in the integration page](https://www.home-assistant.io/integrations/webostv/#action-webostvbutton). Let me push out a patch build for you try again.

I also could use help filling out the default sources lists for these new platforms, if you know of other sources for LG webOS other than Netflix and Prime Video.

**Reply by Nerwyn** [reply]
@mk89pwnz should be fixed in [4.0.3](https://github.com/Nerwyn/android-tv-card/releases/tag/4.0.3).

**Comment by mk89pwnz** [comment]
Only now had time to check it out but it didn't work for me, maybe my use case is different. I have LG C7 with android TV box, so mainly I need android TV integration, but the way volume is controlled is via HDMI I guess because it controls my tv volume not the box and I use then LG integration, this is how my config looks now and working:

Didn't had time to test keyboard, does it must to have adb because android tv box is locked now and can't get into dev settings anymore :(

```yaml
type: custom:android-tv-card
remote_id: remote.android_tv
media_player_id: media_player.lg_c7
rows:
  - - - - power
        - lg_bt
  - - - - home
        - settings
        - null
        - jellyfin
        - youtube
  - - - - touchpad
        - - volume_up
          - null
          - volume_mute
          - null
          - volume_down
  - - - - back
        - previous
        - rewind
        - fast_forward
        - next
        - play_pause
custom_actions:
  - type: button
    name: lg_bt
    entity_id: switch.lg_bt_switch
    icon: mdi:bluetooth
    hold_action:
      action: navigate
      navigation_path: /dashboard-main/lg-c7
    tap_action:
      action: toggle
      target:
        entity_id: switch.lg_bt_switch
    styles: ''
  - type: button
    name: volume_up
    tap_action:
      action: perform-action
      perform_action: webostv.button
      target:
        entity_id: media_player.lg_c7
      data:
        button: VOLUMEUP
    hold_action:
      action: repeat
    icon: mdi:volume-plus
    entity_id: media_player.lg_c7
    value_attribute: volume_level
  - type: button
    name: volume_down
    tap_action:
      action: perform-action
      perform_action: webostv.button
      target:
        entity_id: media_player.lg_c7
      data:
        button: VOLUMEDOWN
    hold_action:
      action: repeat
    icon: mdi:volume-minus
    entity_id: media_player.lg_c7
    value_attribute: volume_level
  - type: button
    name: volume_mute
    tap_action:
      action: perform-action
      perform_action: webostv.button
      target:
        entity_id: media_player.lg_c7
      data:
        button: MUTE
    icon: mdi:volume-mute
    hold_action:
      action: repeat
    entity_id: media_player.lg_c7
    value_attribute: volume_level
styles: ''
keyboard_id: remote.android_tv
platform: Android TV
custom_icons: []
hold_time: 500
```
