### DISCUSSION TITLE
Center default hold behavior

### DISCUSSION THREAD

**Discussion by mk89pwnz** [Nerwyn/universal-remote-card#136] [Q&A]
Anyway to get center button to act like default, when you hold it to get more options, need this in youtube.

**Comment by Nerwyn** [comment]
For which platform? For any platforms like Android TV that use `remote.send_command` for their default keys it add `hold_secs: 0.5` to their request data on hold actions if a separate hold action isn't defined. For other platforms you can redefine the hold action using a custom action for the `center` button or touchpad center.

**Comment by mk89pwnz** [comment]
Android tv, I have such settings for center and it just works as tap, but nothing for hold at least in youtube. 
![Screenshot 2024-09-13 192740](https://github.com/user-attachments/assets/1112618a-f2e2-498b-91a2-d4527fe288b8)

With phone when I hold and it vibrates if I release at that moment it works sometimes, but via browser it never works. tried adding new config same thing.

**Reply by Nerwyn** [reply]
Does it work on your phone if you keep holding and don't release until after it vibrates? I'll have to check and see if the behavior is inconsistent in browser using a mouse as well.

**Reply by mk89pwnz** [reply]
> Does it work on your phone if you keep holding and don't release until after it vibrates? I'll have to check and see if the behavior is inconsistent in browser using a mouse as well.

it just does a tap action and launches a youtube video.

**Reply by Nerwyn** [reply]
What about on other apps or the home screen? I personally use SmartTube so I haven't been able to test the YouTube app in particular.

What if you change the hold action to explicitly set a longer `hold_secs` value (fixed)?

```yaml
hold_action:
  action: perform-action
  perform_action: remote.send_command
  data:
    command: DPAD_CENTER
    hold_secs: 1
```

**Reply by mk89pwnz** [reply]
> What about on other apps or the home screen? I personally use SmartTube so I haven't been able to test the YouTube app in particular.
> 
> What if you change the hold action to explicitly set a longer `hold_secs` value?
> 
> ```yaml
> hold_action:
>   action: perform-action
>   perform_action: remote.send_command
>   data:
>     hold_secs: 1
> ```
If i set hold to this code I get:
![Screenshot 2024-09-13 223542](https://github.com/user-attachments/assets/59db8f4e-78a9-4a40-9a0c-f49d4dd80368)
and nothing happens, then if I remove the code I get vibration but nothing happens. 

So I desided to test with brand new card:
```yaml
type: custom:android-tv-card
rows:
  - navigation_buttons
  - dpad
  - touchpad
  - center
custom_actions: []
remote_id: remote.android_tv
keyboard_id: remote.android_tv
media_player_id: media_player.lg_c7
```
All of them do the same if I hold it vibrates and if I keep holding it does the tap action, but if I manage to release after vibration ends I get the default hold action.

**Reply by Nerwyn** [reply]
Sorry I forgot the to include the command in that example.

```yaml
hold_action:
  action: perform-action
  perform_action: remote.send_command
  data:
    command: DPAD_CENTER
    hold_secs: 1
```

I've tried with multiple devices using both touch and mouse and haven't been able to recreate the issue. Is this just for the YouTube app or all of Android TV? My Google TV isn't letting me open the YouTube app and redirects me to SmartTube so I'm not able to check.
