### DISCUSSION TITLE
Reduce icon size

### DISCUSSION THREAD

**Discussion by templeowls21** [Nerwyn/universal-remote-card#145] [General]
I have the below code. I want to make the icons in the volume line smaller. I couldn't find how to do this in the guide. Any suggestions?

```yaml
type: custom:android-tv-card
rows:
  - - back
    - <br>
    - up
    - <br>
    - home
  - <br>
  - - left
    - center
    - right
  - <br>
  - - <br>
    - <br>
    - down
    - <br>
    - <br>
  - <br>
  - - reverse
    - play
    - forward
  - - <br>
  - - volume_down
    - volume_up
    - volume_mute
    - keyboard
platform: Roku
remote_id: remote.living_room_tv
keyboard_id: media_player.living_room_tv
media_player_id: media_player.living_room_tv
custom_actions: []
```

**Comment by Nerwyn** [comment]
Try adding this to your global styles:

```css
remote-button {
  --size: 16px;
}
```

Change the value of `--size` as needed. See the [appearance](https://github.com/Nerwyn/android-tv-card?tab=readme-ov-file#appearance) section of the README for more details.

**Reply by templeowls21** [reply]
Thanks, is it possible to change the size of only certain icons though?

**Reply by Nerwyn** [reply]
Create a custom action and put the styles there instead.

```css
.icon {
  --size: 16px;
}
```
