### DISCUSSION TITLE
Navigational Wheel to the Right

### DISCUSSION THREAD

**Discussion by coasttech** [Nerwyn/universal-remote-card#153] [Q&A]
<img width="1296" alt="Screenshot 2024-10-24 at 2 44 45 PM" src="https://github.com/user-attachments/assets/7db3d0dd-39f6-4d20-93d2-5eae794cb601">

Is there a way to achieve this because so far I'm not winning..

**Comment by Nerwyn** [comment]
Mashing together the samples from the README and adjusting the rows styled worked for me. I did also have to place it in a wider section (in sections view) and make the card full width, otherwise the navigation buttons don't fit in the card.

```yaml
type: custom:android-tv-card
remote_id: remote.lounge_google_tv
keyboard_id: remote.lounge_google_tv_adb
custom_actions:
  - type: button
    name: center
    tap_action:
      action: key
      key: DPAD_CENTER
    icon: mdi:checkbox-blank-circle
    styles: |-
      :host {
        --icon-color: rgb(94, 94, 94);
        --size: 200px;
        background: rgb(31, 31, 31);
        border-radius: 200px;
        margin: -70px;
        padding: 70px;
      }
  - type: button
    name: up
    tap_action:
      action: key
      key: DPAD_UP
    hold_action:
      action: repeat
    icon: mdi:chevron-up
    styles: |-
      :host {
        --icon-color: rgb(197, 199, 197);
        z-index: 2;
        top: 25px;
        height: 90px;
        width: 300px;
      }
  - type: button
    name: down
    tap_action:
      action: key
      key: DPAD_DOWN
    hold_action:
      action: repeat
    icon: mdi:chevron-down
    styles: |-
      :host {
        --icon-color: rgb(197, 199, 197);
        z-index: 2;
        bottom: 25px;
        height: 90px;
        width: 300px;
      }
  - type: button
    name: left
    tap_action:
      action: key
      key: DPAD_LEFT
    hold_action:
      action: repeat
    icon: mdi:chevron-left
    styles: |-
      :host {
        --icon-color: rgb(197, 199, 197);
        z-index: 2;
        left: 30px;
        height: 170px;
        width: 90px;
      }
  - type: button
    name: right
    tap_action:
      action: key
      key: DPAD_RIGHT
    hold_action:
      action: repeat
    icon: mdi:chevron-right
    styles: |-
      :host {
        --icon-color: rgb(197, 199, 197);
        z-index: 2;
        right: 30px;
        height: 170px;
        width: 90px;
      }
styles: |-
  #row-7 {
    justify-content: center;
  }
  #row-8 {
    justify-content: center;
  }
  #row-9 {
    justify-content: center;
  }
rows:
  - - - - back
        - null
        - home
        - null
        - menu
      - - volume_down
        - null
        - volume_mute
        - null
        - volume_up
      - - rewind
        - null
        - play_pause
        - null
        - fast_forward
      - - netflix
        - disney
        - hulu
        - max
        - primevideo
      - - plex
        - vudu
        - youtube
        - spotify
    - - - keyboard
        - search
      - - navigation_buttons
visibility:
  - condition: screen
    media_query: "(orientation: landscape)"
layout_options:
  grid_columns: full
  grid_rows: auto
```
![image](https://github.com/user-attachments/assets/27f4f237-b827-4136-8323-46f70aebf44f)
