### DISCUSSION TITLE
how to create one remote control for all devices?

### DISCUSSION THREAD

**Discussion by Vladd1980** [Nerwyn/universal-remote-card#155] [General]
how to create one remote control for all devices? Let's say I have several Kodi devices, a TV that is controlled via an IR remote control, an Android TV that is controlled via ADB. Making a separate remote control for each device is extremely inconvenient. Can I just implement a button to switch between devices on one remote control?

**Comment by Nerwyn** [comment]
You can create a Home Assistant helper input select with the different platforms as possible values, use a template to change the value of the global `platform`, and create a custom action to iterate through the input select values.

```yaml
platform: '{{ states("input_select.platform") }}'
custom_actions:
  - icon: mdi:skip-next-circle
    tap_action:
      data:
        cycle: true
      target:
        entity_id: input_select.platform
      action: perform-action
      perform_action: input_select.select_next
    type: button
    autofill_entity_id: true
    entity_id: input_select.platform
    name: change_platform
    value_attribute: state
    haptics: true
```

Default keys and sources that only exist on certain platforms is trickier. You'll have to use templates in custom actions to change their action information based on the platform. All fields are templatable so it should be doable, just ugly.
