### DISCUSSION TITLE
Integration with Unified Remote Server

### DISCUSSION THREAD

**Discussion by jared-a-lloyd** [Nerwyn/universal-remote-card#180] [Q&A] [answered]
I am little confused as to the correct way to set up the integration with urserver. I have setup the hacs plugin for urserver as in [this documentation](https://github.com/DaviPtrs/hass-unified-remote) up to the point of creating/editing remote.yaml. 

Based on the code [here](https://github.com/Nerwyn/android-tv-card/issues/124) and [here](https://github.com/Nerwyn/android-tv-card/blob/9c4b19399e16a926056c181515d9da26571adad4/src/classes/keyboards/unified-remote-keyboard.ts#L18), it looks like the card just needs the name of the server, and the actual remotes it is accessing are auto-filled. Is this correct?

Essentially I am asking *in HA do I need to add remotes in remotes.yaml, if I have added unified_remote to configuration.yaml*?

For reference here is the card I am trying out :
```yaml
type: custom:android-tv-card
platform: Unified Remote
custom_actions: []
rows:
  - touchpad
  - keyboard
remote_id: HomeServer
keyboard_id: HomeServer
```

And this is the relevant HA configuration.yaml section:
```yaml
unified_remote:
  hosts:
    - host: <ip-address>
    - port: <port>
    - name: HomeServer
  retry_delay: 60
```
