### DISCUSSION TITLE
Change icon color

### DISCUSSION THREAD

**Discussion by Bagareal** [Nerwyn/universal-remote-card#186] [Q&A]
Hello, 
i'm using this integration only to open Netflix and Jellyfin on my tv (By the way, thank you so much!). The only thing that i can't do is change color on the icons. The Icons are white and i would like to change color or maybe change them. I read the docs but i can't make it work. Is there some kind person that can explain to me what i'm doing wrong? 

Thanks in advance.

**Comment by Nerwyn** [comment]
Several examples ([like this one](https://github.com/Nerwyn/android-tv-card?tab=readme-ov-file#example-9)) include icon modifications such as color. The most direct way is to create custom actions for these icons, (they'll autofill with their default action information when you enter their names) and then include the icon CSS styles there in the appearance pane.

```css
.icon {
  color: #E50914;
}
``` 

I did just realize that you can color specific icons in the global CSS styles without custom actions if you want to do less config changes.

```css
[title="netflix"] {
  --icon-color: #E50914;
}
```

**Reply by Bagareal** [reply]
![screenshot](https://github.com/user-attachments/assets/162bf499-46c1-48c9-9a1a-3aea1811d066)
I have a created a single button yo open netflix but i don't understand where i have to insert the code about the color:

```yaml
type: custom:android-tv-card
remote_id: remote.android_tv
media_player_id: media_player.android_tv
custom_actions:
  - type: button
    name: Netflix
    tap_action:
      action: adb_command
      command: am start -n com.netflix.ninja/.MainActivity
    icon: mdi:netflix
keyboard_id: remote.android_tv
grid_options:
  columns: 4
  rows: auto
autofill_entity_id: true
haptics: true
rows:
  - - netflix
custom_icons:
  - name: netflix
    path: https://www.svgrepo.com/svg/303196/netflix-2-logo
```
