### DISCUSSION TITLE
Harmony hub commands for custom keys with custom icons, beginner struggling

### DISCUSSION THREAD

**Discussion by Alllfff** [Nerwyn/universal-remote-card#20] [Q&A]
I would like to have custom keys with custom commands and icons as part of this card, but struggling to do so. 
If i make a simple button and put this code in it, the Harmony changes Receiver's input to Game:
```
tap_action:
  action: call-service
  service: remote.send_command
  target:
    device_id: 8090654541f507fac67237df8f26713a
  data:
    command: InputGame
    device: Teac AV Receiver
```
so how can I implement this into the remote card please?
```
type: custom:android-tv-card
title: AV
custom_keys:
  inputXBox:
    icon: mdi:microsoft-xbox
    service: remote.send_command
    target:
      device_id: 8090654541f507fac67237df8f26713a
    data:
      command: InputGame
      device: Teac AV Receiver
rows:
  - - volume_up
    - up
    - power
  - - left
    - home
    - right
  - - volume_down
    - down
    - inputXbox
```
