### DISCUSSION TITLE
How turn on/off a light if I play/pause movie

### DISCUSSION THREAD

**Discussion by bhavinafricawala** [Nerwyn/universal-remote-card#232] [General]
Is there a way I can turn on/off a light if I play/pause or press home button on the remote I created for my nvidia shield. Here is my code 
```yaml
type: custom:universal-remote-card
rows:
  - - home
    - power
    - back
  - - netflix
    - youtube
    - plex
    - primevideo
    - kodi
  - touchpad
remote_id: remote.shield
custom_actions: []
media_player_id: media_player.shield_2
custom_icons: []
style: |
  #netflix::part(icon) {
    color:red;
  }
styles: |-
  #netflix::part(icon) {
    color: #E50914;
  }
  #youtube::part(icon) {
    color: #FF0000;
  }
  #plex::part(icon) {
    color: #e5a00d;
  }
  #primevideo::part(icon) {
    color: #0779FF;
  }
  #kodi::part(icon) {
    color: #578FCA;
  }
  #power::part(icon) {
    color: #347433;
  }
```

**Comment by Nerwyn** [comment]
You have to use custom actions to either create a new button or remap a new one to do so. You can't use the `Perform Action` action to call multiple actions, but you can either create a script to fire multiple actions in Home Assistant and call that, or fire actions using the `Evaluate JS` action and the `this.hass.callService` function.

**Comment by Forsskieken** [comment]
Yes what I did was this:
```
custom_actions:
  - type: button
    name: netflix
    icon: netflix
    tap_action:
      action: call-service
      service: script.netflix_with_lights
```
```
custom_icons:
  - name: netflix
    path: >-
      M 8.966 22.563 H 4.001 V 1.5069 H 9 L 14.958 12.985 V 1.5069 h 5 V 22.4931 H 15 L 8.962 9.948 Z
```



in my script.yaml I have this
```
netflix_with_lights:
  alias: "Launch Netflix + TV Time Lights"
  sequence:
    - action: media_player.play_media
      target:
        entity_id: media_player.shield    # <-- replace if your Shield entity_id differs
      data:
        media_content_type: app
        media_content_id: com.netflix.ninja
    - choose:
        - conditions:
            - condition: state
              entity_id: light.living
              state: "on"
          sequence:
            - service: light.turn_on
              target:
                entity_id: light.living
              data:
                effect: "TV time"
      default:
        - service: light.turn_on
          target:
            entity_id: light.living
          data:
            effect: "TV time"
```
