### DISCUSSION TITLE
Hold action custom keys

### DISCUSSION THREAD

**Discussion by dipseth** [Nerwyn/universal-remote-card#30] [Q&A] [answered]
will something like this work within a custom key config?
 I'd like to add something like this for some custom keys, but it seems only possible for touchpad based on README .

```
hold_action:
          action: call-service
          service: some.service
          data:
            
          target:
            entity_id:
```
