### DISCUSSION TITLE
Start any app

### DISCUSSION THREAD

**Discussion by Torpedro1978** [Nerwyn/universal-remote-card#37] [Q&A]
Hi!
I'm sure, this is very obvious to most of you, but i can't fugure it out:

How can i start any of the other installed apps.
I want to start VLC ;-)

**Comment by Nerwyn** [comment]
[See tronikos' deep linking guide](https://community.home-assistant.io/t/android-tv-remote-app-links-deep-linking-guide/567921) and create custom sources using the deep links found there.

**Comment by Californian** [comment]
I use this instead of deep links, since deep links are limited and don't work for apps all apps (e.g. jellyfin).

Caveat: you have to grab all the logo images manually and add them to your local storage at, in the example below, `/www/images`.

```
type: grid
cards:
  - type: picture-elements
    image: /local/images/white-background.svg
    elements:
      - type: image
        image: /local/images/jellyfin-logo.svg
        style:
          left: 47%
          top: 47%
          width: 94%
          margin: 3% 3% 3% 3%
        tap_action:
          action: call-service
          service: media_player.select_source
          target:
            device_id: 0123456789abcdef
          data:
            source: org.jellyfin.androidtv
      ...
```
