### DISCUSSION TITLE
Samsung TV Integration

### DISCUSSION THREAD

**Discussion by coasttech** [Nerwyn/universal-remote-card#42] [General]
I have this integrated already in Home Assistant. Is there a way I could use android-tv-card to control the volume using that device?

**Comment by Nerwyn** [comment]
[This one right?](https://www.home-assistant.io/integrations/samsungtv/#remote)

Try this:

```yaml
remote_id: remote.samsung_tv
custom_keys:
  volume_up:
    key: KEY_VOLUP
  volume_down:
    key: KEY_VOLDOWN
```

**Reply by coasttech** [reply]
Yes 

Am I able to have two remote_id:'s?

adding the Samsung removes the android functionality.

**Reply by Nerwyn** [reply]
Nope, but you can create custom keys that use service calls to call `remote.send_command` directly.

```yaml
custom_keys:
  volume_up:
    service: remote.send_command
    data:
      entity_id: remote.samsung_tv
      command: KEY_VOLUP
  volume_down:
    service: remote.send_command
    data:
      entity_id: remote.samsung_tv
      command: KEY_VOLDOWN
```
