### DISCUSSION TITLE
Q: Could this code be adapted for other media players?

### DISCUSSION THREAD

**Discussion by houser42** [Nerwyn/universal-remote-card#5] [Ideas]
Just found this very promising  bit of code. 
I have an Android TV (Sony Bravia KD.xx) that I am experimenting on with this. 
No luck so far. Have the usual remote working with the same entity.

My main question:
I also have two other media players that I am wondering how difficult it would be to adapt this code for:
Kodi and Apple TV. 
I want to program very similar swipe gestures/touchpad remotes for all me HT gear, as I have in the current
environment that I am migrating from at some point (iRule)
Any comments appreciated. Many thanks!

**Comment by Nerwyn** [comment]
Copying over our notes from the community forums page.

Apple TV
```yaml
type: custom:android-tv-card
remote_id: remote.apple_tv
_row_1:
  - power
  - play
  - pause
  - menu
navigation_row: touchpad
custom_keys:
  up:
    icon: mdi:chevron-up
    key: up
  down:
    icon: mdi:chevron-down
    key: down
  left:
    icon: mdi:chevron-left
    key: left
  right:
    icon: mdi:chevron-right
    key: right
  center:
    icon: mdi:checkbox-blank-circle
    key: select
  power:
    icon: mdi:power
    key: suspend # or wakeup? idk I'm an Android user.
  play:
    icon: mdi:play
    key: play
  pause:
    icon: mdi:pause
    key: pause
  menu:
    icon: mdi:menu
    key: menu
```

Kodi
```yaml
type: custom:android-tv-card
navigation_row: touchpad
custom_keys:
  up:
    icon: mdi:chevron-up
    service: kodi.call_method
    service_data:
      entity_id: media_player.kodi
      method: Input.Up
  down:
    icon: mdi:chevron-down
    service: kodi.call_method
    service_data:
      entity_id: media_player.kodi
      method: Input.Down
  left:
    icon: mdi:chevron-left
    service: kodi.call_method
    service_data:
      entity_id: media_player.kodi
      method: Input.Left
  right:
    icon: mdi:chevron-right
    service: kodi.call_method
    service_data:
      entity_id: media_player.kodi
      method: Input.Right
  # continue in a similar manner for other commands
```

**Comment by houser42** [comment]
Just confirming that these are working great. Fab!
I will make a full working remote for kodi and post it here at some point soon.

**Comment by houser42** [comment]
Question:
As I start work on this, two things that I wonder if they are in the code already or can be tweaked or added:
1. double-tap on the touchpad
2. full transparency for the touchpad area
Can it be done? If not I guess this is something for the wishlist?
Many thanks!

**Comment by Nerwyn** [comment]
> 1. double-tap on the touchpad

This is actually a feature of the [tv-card](https://github.com/usernein/tv-card/tree/master) that this was forked from, but it doesn't seem to work for me. Considering that the code that deals with double clicks hasn't been modified from the parent I wonder if it was working before the fork.

> 2. full transparency for the touchpad area

You can do this using [card-mod](https://github.com/thomasloven/lovelace-card-mod). I probably won't add a separate input for this as it falls under theming which can all be done using card-mod.
```yaml
card_mod:
  style: |
    :host {
      --ha-card-background: #7096d540;
    }
    toucharea {
      background: #244cc650;
    }
```

**Reply by houser42** [reply]
Understood!
> 1. double-tap on the touchpad.

I have tried adding it back in various ways by way of custom keys and in some other ways. No luck so far..

> 2. full transparency for the touchpad area.

Your suggestion here works great. Many thanks again!

**Reply by Nerwyn** [reply]
After playing around with double click some more I found that it does work, but it triggers the single click event first. Making it so that by default it clicks on something and then immediately goes back, making it look like nothing happened. This is a bug.
https://github.com/Nerwyn/android-tv-card/issues/9

**Reply by houser42** [reply]
> This is a bug.

I see. I assume something that would need to be fixed upstream and nothing you can squash?

**Reply by Nerwyn** [reply]
Fixed in [v1.4.2](https://github.com/Nerwyn/android-tv-card/releases/tag/v1.4.2). Double clicks are now disabled by default, but when enabled will no longer also trigger the single click event.

**Reply by Nerwyn** [reply]
You have to set `double_click_keycode` to the custom key name at the bottom level, then remap that key in custom keys, like this:
```yaml
## Apple TV:
type: custom:android-tv-card
remote_id: remote.appletv
navigation_row: touchpad
touchpad_height: 200px
enable_double_click: true
double_click_keycode: menu
custom_keys:
  menu: 
    icon: mdi:chevron-up
    key: menu
  up:
    icon: mdi:chevron-up
    key: up

## Kodi:
type: custom:android-tv-card
navigation_row: touchpad
touchpad_height: 200px
enable_double_click: true
double_click_keycode: back
custom_keys:
  back:
    icon: mdi:chevron-right
    service: kodi.call_method
    service_data:
      entity_id: media_player.kodi
      method: Input.Back
  up:
    icon: mdi:chevron-up
    service: kodi.call_method
    service_data:
      entity_id: media_player.kodi
      method: Input.Up
```

**Reply by houser42** [reply]
I see. Thanks for that!

So I am working on this for four devices now. Some observations:
1. The Sony Bravia TV works 100% on a MacBook desktop and one iPhone client. Including double-tap back.

2. The Apple TV touchpad works 100% including double-tap back.
 Still appears like a 1-tap as you described.  Timing issue?

3. The Kodi touchpad works 100% except double-tap back.
I see  a quick back and then return to where the back command was issued that maybe looks like a  timing issue? Too slow? 
Still appears like a 1-tap as you described.  

4. The Denon touchpad also  works 100% except double-tap back as the other two. 
I see  a quick back and then return to where the back command was issued that maybe looks like a  timing issue? Too slow? 

No consistent log errors. This is a dev VirtualBox system so possibly some inconsistencies that I need to iron out myself, as I am new to HA. But as the Bravia/Android TV works there seems to be something else going on that is beyond my current skillset on this. Many thanks again!

**Reply by Nerwyn** [reply]
Inconsistent behavior between devices is likely either a browser caching issue or lack of browser support for double click and not an issue with your Home Assistant host. I lean towards the former because [according to W3 schools it should be supported by all browsers](https://www.w3schools.com/jsref/event_ondblclick.asp). Have you tried clearing your web browser or Home Assistant app cache?

**Comment by Nerwyn** [comment]
@houser42 can you post your full Kodi and AppleTV remote configs and some screenshots? I want to add them to the README examples.

**Reply by houser42** [reply]
Sure. 
I am new to HA so the gui is nowhere near done, but here is some basic work in progress for Kodi, an Apple TV and a Sony Bravia TV. I have not managed to get my Marantz AVR working with the touchpad as yet and will add that when I do. If someone sees this and has that working, please post it here also. 
Also added pic of a work in progress Apple TV remote GUI with the disclaimer that the double-tap-is not working yet on my system as discussed earlier in this thread on Apple TV and Kodi. 
I will probably do all buttons outside the touchpad for flexibility and design reasons.
Ah well, this is probably the simple kind of thing I am going for with the remotes:

![appletvtouch1wip](https://github.com/Nerwyn/android-tv-card/assets/15192440/e68299da-894e-407b-aece-c7fef7ab79bf)

And here is the code for three work in progress touchpads.

```
## Kodi:
type: custom:android-tv-card
navigation_row: touchpad
touchpad_height: 200px
enable_double_click: true
double_click_keycode: back
custom_keys:
  up:
    icon: mdi:chevron-up
    service: kodi.call_method
    service_data:
      entity_id: media_player.kodi
      method: Input.Up
  down:
    icon: mdi:chevron-down
    service: kodi.call_method
    service_data:
      entity_id: media_player.kodi
      method: Input.Down
  left:
    icon: mdi:chevron-left
    service: kodi.call_method
    service_data:
      entity_id: media_player.kodi
      method: Input.Left
  right:
    icon: mdi:chevron-right
    service: kodi.call_method
    service_data:
      entity_id: media_player.kodi
      method: Input.Right
  center:
    icon: mdi:kodi
    service: kodi.call_method
    service_data:
      entity_id: media_player.kodi
      method: Input.Select
  back:
    icon: mdi:kodi
    service: kodi.call_method
    service_data:
      entity_id: media_player.kodi
      method: Input.Back

## Apple TV:
type: custom:android-tv-card
remote_id: remote.appletv
navigation_row: touchpad
touchpad_height: 200px
enable_double_click: true
double_click_keycode: menu
custom_keys:
  up:
    icon: mdi:chevron-up
    key: up
  down:
    icon: mdi:chevron-down
    key: down
  left:
    icon: mdi:chevron-left
    key: left
  right:
    icon: mdi:chevron-right
    key: right
  center:
    icon: mdi:checkbox-blank-circle
    key: select
  play:
    icon: mdi:play
    key: play
  pause:
    icon: mdi:pause
    key: pause
  menu:
    icon: mdi:apple
    key: menu

## Sony Bravia KD.xx TV (this one works 100%, including double-tap-back):
type: custom:android-tv-card
remote_id: remote.sony_kd_75xf8596
navigation_row: touchpad
enable_double_click: true
double_click_keycode: back
custom_keys:
  up:
    icon: mdi:chevron-up
    key: Up
  down:
    icon: mdi:chevron-down
    key: Down
  left:
    icon: mdi:chevron-left
    key: Left
  right:
    icon: mdi:chevron-right
    key: Right
  center:
    icon: mdi:enter
    key: DpadCenter
  back:
    icon: mdi:play
    key: Back

## Marantz:
type: custom:android-tv-card
entity_id: media_player.marantz_sr7013
navigation_row: touchpad
touchpad_height: 200px
enable_double_click: true
double_click_keycode: back
custom_keys:
  down:
    service: denonavr.get_command
    service_data:
      entity_id: media_player.marantz_sr7013
      command: /goform/formiPhoneAppDirect.xml?MNCDN
  up:
    service: denonavr.get_command
    service_data:
      entity_id: media_player.marantz_sr7013
      command: /goform/formiPhoneAppDirect.xml?MNCUP
  left:
    service: denonavr.get_command
    service_data:
      entity_id: media_player.marantz_sr7013
      command: /goform/formiPhoneAppDirect.xml?MNCLT
  right:
    service: denonavr.get_command
    service_data:
      entity_id: media_player.marantz_sr7013
      command: /goform/formiPhoneAppDirect.xml?MNCRT
  center:
    service: denonavr.get_command
    service_data:
      entity_id: media_player.marantz_sr7013
      command: /goform/formiPhoneAppDirect.xml?MNENT
  back:
    service: denonavr.get_command
    service_data:
      entity_id: media_player.marantz_sr7013
      command: /goform/formiPhoneAppDirect.xml?MNRTN

**Reply by Nerwyn** [reply]
Thanks for the examples! I'll add them to the README.

> Below is the cursor down command that I built and that now works in a simple button in HA for most Denon and Marantz devices.
Could you suggest how to place it into your touchpad code please?

You mean as a directional down? It would be the same as any other down remap.
```yaml
custom_keys:
  down:
    service: denonavr.get_command
    service_data:
      entity_id: media_player.marantz_sr7013
      command: /goform/formiPhoneAppDirect.xml?MNCDN
```

**Reply by houser42** [reply]
Yes that works too!
I have added the Marantz/Denon touchpad code to the examples.
The Marantz is very quick to respond videowise so I can clearly see that the back command happens, but then immediately goes back to where the back command was issued. 
I would wager that that is what is happening with the Kodi and Apple TV double-tap-backs as well. Exactly as you described the initial issue. Maybe revisit it when you have time?
Ah well!
This is really great, thanks very much again!

**Reply by Nerwyn** [reply]
Thanks! I'll add it to the README later.

After messing around some more I found that if your double click is slow enough there's a window where it will still consider a click both a double and a single click. I need to either increase the single click timeout delay (which will make single clicks even less responsive) or decrease the default double click interval (which I'll have to research more on how to do). Thanks for your feedback, I'll make another bug for this.

https://github.com/Nerwyn/android-tv-card/issues/11

But also in the meanwhile, try playing around with how fast your double clicks are and see if that changes anything.

**Reply by houser42** [reply]
Sure. I am however  keenly aware of the double-tap as it is second nature to me, having used it for `back` as long as it has been possible to design a mobile phone-based touch remote ;)  Have also developed professionally for hi-end home theatre. I can assure you It is not possible to produce a double-tap that gives the correct results here in my setup. My only factor of concern is that I am new to HA and am running it on a Virtualbox. I suppose something could act up in there, but it is generally snappy and stable so that seems unlikely. 
If others report success I will stand corrected ;) 
Many thanks again!

**Reply by Nerwyn** [reply]
@houser42 I just released [v1.4.4](https://github.com/Nerwyn/android-tv-card/releases/tag/v1.4.4), which should prevent the single and double clicks both triggering on slow double clicks issue. I'm not sure if this will fix your other issues with double tap not triggering at all and I'm not sure if I can fix that, but hopefully it makes double tap more consistent.

**Reply by houser42** [reply]
Hello,
I note the change, and in my view and on my system, the response is now too slow.
The double-tap issue is also still there as before. Do with this what you will.
In my experience the responsiveness was better in the version before, but perhaps you are fixing something for other platforms. Many thanks.

**Reply by Nerwyn** [reply]
That's really weird. It's much more responsive and consistent in my testing. I'm not sure how to proceed here. You're sure you cleared cache?

**Reply by houser42** [reply]
Yes, I am sure. The only difference here is that I see the same behaviour more clearly.
On a Macbook I think I see it the back, then back to where the double-tap-back was issued more clearly. The MacBook is more responsive than the iPhone app.

**Reply by Nerwyn** [reply]
I've been doing my testing on Windows and Android. I'll try to borrow my girlfriend's MacBook and iPhone later this week to see how it works on her Apple devices.

**Reply by Nerwyn** [reply]
Bad news @houser42 . I tested on some MacBooks and double click was working fine for me. I also did a ton of logic rewrites and testing on multiple iPhones and double clicks did not work with any version of the app. At this point I'm convinced that iPhone does not support double clicks. I can look into more hacky methods to implement double clicks in the future now that I was given an old iPhone SE to use for testing but no promises.

**Reply by houser42** [reply]
Thanks @Nerwyn 
Not bad news at all, these are luxury items;) My Home theatre app is up and running and has a button for back ;)
I agree that the double-taps are working ok on MacBooks after cleaning up caches and my development of my first bit of work in HA. The mobiles are however by far the most important aspect for me for the stuff I do.

My suggested features/settings for touchpad if/when the HA iOS app gets the required functionality
is in the little list below. I am aware it is unlikely that you have the time to code that from scratch
but if/when the hooks become available in the HA iOS app, take advantage and add them?
This is how millions of people are used to using their mobiles so I would assume it will be a priority for the HA apps
at some point. Thanks for a really, really useful bit of code. Very happy with it!
 
1. Double-tap
2. Two finger tap
3. Two finger double-tap
4. Two-finger swipes l-r-u-d
5. Acceleration in lists from fast swipes
Are any or all of these working on Android if I may ask?
Can any or all of these be used on the trackpads on laptops and MacBooks?

Be safe, be well

**Reply by Nerwyn** [reply]
> 1. Double-tap
> 2. Two finger tap
> 3. Two finger double-tap
> 4. Two-finger swipes l-r-u-d
> 5. Acceleration in lists from fast swipes
>     Are any or all of these working on Android if I may ask?
>     Can any or all of these be used on the trackpads on laptops and MacBooks?

Could you make feature requests for all of these under the issues tab with more information on each? Some make sense but others like acceleration I don't fully understand.

I have no idea which devices and browsers any of them work with. I'm a backend engineer by trade and the majority of my frontend experience comes from side projects like this. Double click isn't really used by any websites, which is probably why iPhones do not support it. The Home Assistant iOS app doesn't support it because Apple doesn't support it, and I doubt that they ever will. If I do ever get it working on iPhone it'll be using some weird logic involving recent single click frequency.

**Reply by houser42** [reply]
Sure.
Not sure I understand your points though..
These swipe gestures are supported in various apps on iPhone /iOs as well as on the touchpad on Macs going  back more than ten years. By acceleration I just mean the standard feature on most iPhone and I would assume Android apps, that when you swipe faster a list will scroll faster. That type of standard behaviour that simplifes navigating long lists such as those in a large movie library in a mediaplayer in HA.
It is just the HA app that appears to not support them just yet for various codely reasons..
I am just suggesting these get added to your android card when it eventually becomes available in the HA app which I am assuming it will at some point sooner or later. I am not expecting you to code anything from scratch, just consider using the hooks when they appear. I truly appreciate what your card does as-is!

Be safe, be well

**Reply by Nerwyn** [reply]
The HA app is just a web browser and the HA UI is just a hosted website. When you're using the Home Assistant app, what you're really doing is accessing your own self hosted website, not an app. Therefore all of the touch and swipe gestures that work in most apps won't work in Home Assistant. It isn't the app or iOS that needs to support more advanced touch controls, it's the web browser and iOS webview. iOS doesn't support things like double click and possibly multi touch on websites because those actions are reserved for iOS functionality like zoom and scroll.

**Reply by houser42** [reply]
Ok. I see your point. Perhaps the fact that the browsers on both iOS and MacOS support all these swipe gestures now does not help in this case? Perhaps the HA app could support things like he Apple webkit a bit more and whatever the relevant similar framework  code is called on Android?
Ah well.  This is well beyond my skillset, and I am just hoping for more gestures in the  HA apps, one way or another, sooner or later as swipe gestures is the way to go for home theatre remotes IMHO.
But very happy with what we have today also ;)
Be safe, be well

**Comment by dgoodwin430** [comment]
Could this be adapted to work with Roku players?

**Reply by Nerwyn** [reply]
Yup! The Roku integration uses the same service as Android TV remote so you should be able to create custom actions using the information found on the [Home Assistant Roku integration page](https://www.home-assistant.io/integrations/roku/) for keys, and the `call-service` action for sources. Based on the information there this should work.
```yaml
type: custom:android-tv-card
remote_id: remote.roku
slider_id: media_player.roku
custom_actions:
  back:
    tap_action:
      action: key
      key: back
  backspace:
    tap_action:
      action: key
      key: backspace
  channel_down:
    tap_action:
      action: key
      key: channel_down
  channel_up:
    tap_action:
      action: key
      key: channel_up
  down:
    tap_action:
      action: key
      key: down
  enter:
    tap_action:
      action: key
      key: enter
  find_remote:
    tap_action:
      action: key
      key: find_remote
  forward:
    tap_action:
      action: key
      key: forward
  home:
    tap_action:
      action: key
      key: home
  info:
    tap_action:
      action: key
      key: info
  input_av1:
    tap_action:
      action: key
      key: input_av1
  input_hdmi1:
    tap_action:
      action: key
      key: input_hdmi1
  input_hdmi2:
    tap_action:
      action: key
      key: input_hdmi2
  input_hdmi3:
    tap_action:
      action: key
      key: input_hdmi3
  input_hdmi4:
    tap_action:
      action: key
      key: input_hdmi4
  input_tuner:
    tap_action:
      action: key
      key: input_tuner
  left:
    tap_action:
      action: key
      key: left
  literal:
    tap_action:
      action: key
      key: literal
  play:
    tap_action:
      action: key
      key: play
  power:
    tap_action:
      action: key
      key: power
  replay:
    tap_action:
      action: key
      key: replay
  reverse:
    tap_action:
      action: key
      key: reverse
  right:
    tap_action:
      action: key
      key: right
  search:
    tap_action:
      action: key
      key: search
  select:
    tap_action:
      action: key
      key: select
  up:
    tap_action:
      action: key
      key: up
  volume_down:
    tap_action:
      action: key
      key: volume_down
  volume_mute:
    tap_action:
      action: key
      key: volume_mute
  volume_up:
    tap_action:
      action: key
      key: volume_up
  primevideo:
    tap_action:
      action: call-service
      service: media_player.select_source
      target:
        entity_id: media_player.roku
      data:
        source: "Prime Video"
  disney:
    tap_action:
      action: call-service
      service: media_player.select_source
      target:
        entity_id: media_player.roku
      data:
        source: "Disney Plus"
  hulu:
    tap_action:
      action: call-service
      service: media_player.select_source
      target:
        entity_id: media_player.roku
      data:
        source: "Hulu"
  spotify:
    tap_action:
      action: call-service
      service: media_player.select_source
      target:
        entity_id: media_player.roku
      data:
        source: "Spotify"
  youtube:
    tap_action:
      action: call-service
      service: media_player.select_source
      target:
        entity_id: media_player.roku
      data:
        source: "YouTube"
```
