### DISCUSSION TITLE
Adding TiviMate

### DISCUSSION THREAD

**Discussion by TurboTronix** [Nerwyn/universal-remote-card#52] [General]
Is there a way to add a TiviMate button?

**Comment by Nerwyn** [comment]
Unfortunately it may not be possible. I was going to say to use the deep linking guide to find the deep link for it but according to [this post](https://community.home-assistant.io/t/android-tv-remote-app-links-deep-linking-guide/567921/205) in the guide thread the app does not support deep linking.

**Comment by nikolaisenha** [comment]
Are you using Android or Apple TV? For Apple TV atleast there is no need for deeplinks as the Apple TV uses the app nameof the app😊

**Comment by zimmra** [comment]
> Is there a way to add a TiviMate button?

Need to add this to your custom actions

Must be used with the ADB media player entity, not the newer 'Android Remote' entity/integration. You can run both concurrently

```yaml
   tivimate:
    icon: mdi:television-classic
    style:
      background: '#3C87CB'
    tap_action:
      action: call-service
      data:
        entity_id: media_player.living_room_shield_adb
        source: ar.tvplayer.tv
      service: media_player.select_source
```
