### DISCUSSION TITLE
My Clean Remote

### DISCUSSION THREAD

**Discussion by Californian** [Nerwyn/universal-remote-card#57] [Show and tell]
Hi friends,

I spent way too much time on this a little while back, so I figured I'd share. It's not super well-generalized/DRY so it's a bit tedious to edit, but I hope it's of use to someone else here!

![tv-card](https://github.com/Nerwyn/android-tv-card/assets/1079539/feee4e25-7cb8-4659-a051-cc53fbab25b8)

Note that you'll have to get the images for the logos manually (white circle and white background svgs are below) and put them in `/www/images`, as well as create an `input_boolean` for the D-pad toggle. I actually made a separate toggle for each user and copied a bunch of yaml, but there are cleaner ways (I was in a hurry by the end of this). You'll obviously need to change the IDs to match your setup as well.

The multi-touch volume and seek were added just now without testing fyi.

I tried to put as many of the controls on the bottom as possible so on mobile it would be easier to reach, but unfortunately the tabs were too annoying so I left them at the top.

If I had spent more time on this, I would have changed the backgrounds to black in dark mode. I also would have fixed some of the padding and rounding.

I'm happy to clean this up/remove the unrelated parts and add it to the examples in the readme if that's desired, but I'll let the maintainers decide on that before putting in the effort.

I also want to send a huge thanks to the maintainers and contributors (and those of the previous projects on which this is based); this project (especially gesture controls) has made my TV viewing experience much much nicer, and I rarely reach for the physical remote now because I don't even need to look down for most of what I need to do.

Happy remote controlling :smile:

```yaml
type: custom:mod-card
card_mod:
  style: null
card:
  type: custom:tabbed-card
  tabs:
    - card:
        type: custom:stack-in-card
        mode: vertical
        cards:
          - type: custom:mini-media-player
            entity: media_player.living_room_tv_universal
            group: false
            toggle_power: true
            name: Now Playing
            icon: mdi:television-classic
            scale: 1.2
            hide:
              name: false
              power: true
              controls: true
              volume: true
              mute: true
              icon_state: false
              runtime: false
              runtime_remaining: false
          - type: vertical-stack
            cards:
              - type: custom:android-tv-card
                remote_id: remote.living_room_tv
                media_player_id: media_player.living_room_tv_universal
                keyboard_id: media_player.living_room_tv_adb
                slider_id: media_player.living_room_tv_universal
                enable_button_feedback: true
                rows:
                  - - navigation_touchpad
                  - - - left
                    - - up
                      - null
                      - null
                      - center
                      - null
                      - null
                      - down
                    - - right
                custom_actions:
                  up:
                    multi_tap_action:
                      action: key
                      key: VOLUME_UP
                  down:
                    multi_tap_action:
                      action: key
                      key: VOLUME_DOWN
                  left:
                    multi_tap_action:
                      action: key
                      key: MEDIA_REWIND
                  right:
                    multi_tap_action:
                      action: key
                      key: MEDIA_FAST_FORWARD
                  center:
                    double_tap_action:
                      action: key
                      key: BACK
                    multi_tap_action:
                      action: key
                      key: MUTE
                    multi_double_tap_action:
                      action: key
                      key: HOME
                    multi_hold_action:
                      action: call-service
                      service: input_boolean.toggle
                      target:
                        entity_id: input_boolean.movie_mode

                touchpad_style:
                  height: 100%
                  aspect-ratio: 1 / 1
                  background-image: >-
                    url("/local/images/white-circle.svg")
                  background-size: 40px
                  background-repeat: no-repeat
                  background-position: center
                  opacity: 0.9
                card_mod:
                  style: >
                    {% if
                    states('input_boolean.living_room_tv_remote_d_pad_is_enabled')
                    == "on" %} ha-card > div:nth-child(1) {
                      display: none;
                    } {%endif%}

                    {% if
                    states('input_boolean.living_room_tv_remote_d_pad_is_enabled')
                    == "off" %} ha-card > div:nth-child(2) {
                      display: none;
                    } {%endif%}

                    ha-card > div:nth-child(1), ha-card > div:nth-child(1) >
                    toucharea, ha-card > div:nth-child(2) {
                      height: 100%;
                      aspect-ratio: 1 / 1;
                    }

                    ha-card > div:nth-child(1) > toucharea {
                      background-image: url("/local/images/white-circle.svg");
                      background-size: 40px;
                      background-repeat: no-repeat;
                      background-position: center;
                      opacity: 0.9;
                    }
              - type: custom:mod-card
                style:
                  hui-horizontal-stack-card$: |
                    #root > button-card {
                      margin: 0;
                    }
                card:
                  type: horizontal-stack
                  cards:
                    - type: custom:button-card
                      entity: >-
                        input_boolean.living_room_tv_remote_d_pad_is_enabled
                      show_name: false
                      color_type: card
                      icon: mdi:gesture-tap-box
                      styles:
                        card:
                          - height: 64px
                          - border-radius: >-
                              var(--ha-card-border-radius,12px) 0px 0px
                              var(--ha-card-border-radius,12px)
                          - border-color: >-
                              var(--state-inactive-color,
                              var(--state-input_boolean-off-color,
                              var(--state-disabled-color)))
                          - border-width: 8px 0px 8px 8px
                          - padding: 4px
                      state:
                        - value: "on"
                          styles:
                            card:
                              - background-color: >-
                                  var(--state-inactive-color,
                                  var(--state-input_boolean-off-color,
                                  var(--state-disabled-color)))
                            icon:
                              - color: white
                        - value: "off"
                          styles:
                            card:
                              - background-color: >-
                                  var(--switch-checked-button-color,
                                  var(--state-input_boolean-on-color,
                                  var(--state-active-color)))
                            icon:
                              - color: black
                      tap_action:
                        action: call-service
                        service: input_boolean.toggle
                        data:
                          entity_id: >-
                            input_boolean.living_room_tv_remote_d_pad_is_enabled
                    - type: custom:button-card
                      entity: >-
                        input_boolean.living_room_tv_remote_d_pad_is_enabled
                      show_name: false
                      icon: mdi:camera-control
                      styles:
                        card:
                          - height: 64px
                          - border-radius: >-
                              0px var(--ha-card-border-radius,12px)
                              var(--ha-card-border-radius,12px) 0px
                          - border-color: >-
                              var(--state-inactive-color,
                              var(--state-input_boolean-off-color,
                              var(--state-disabled-color)))
                          - border-width: 8px 8px 8px 0px
                          - padding: 4px
                      state:
                        - value: "on"
                          styles:
                            card:
                              - background-color: >-
                                  var(--switch-checked-button-color,
                                  var(--state-input_boolean-on-color,
                                  var(--state-active-color)))
                            icon:
                              - color: black
                        - value: "off"
                          styles:
                            card:
                              - background-color: >-
                                  var(--state-inactive-color,
                                  var(--state-input_boolean-off-color,
                                  var(--state-disabled-color)))
                            icon:
                              - color: white
                      tap_action:
                        action: call-service
                        service: input_boolean.toggle
                        data:
                          entity_id: >-
                            input_boolean.living_room_tv_remote_d_pad_is_enabled
              - type: custom:android-tv-card
                remote_id: remote.living_room_tv
                media_player_id: media_player.living_room_tv_universal
                keyboard_id: media_player.living_room_tv_adb
                enable_button_feedback: true
                rows:
                  - - back
                    - null
                    - home
                    - null
                    - keyboard
          - type: custom:mini-media-player
            entity: media_player.living_room_tv_universal
            group: false
            toggle_power: true
            volume_stateless: true
            icon: mdi:television-classic
            scale: 1.2
            tap_action:
              action: call-service
              service: media_player.turn_on
              service_data:
                entity_id: media_player.living_room_tv_universal
            hide:
              name: true
              icon: true
              info: true
              power_state: false
              volume_level: true
      attributes:
        label: Controls
        icon: mdi:remote-tv
    - card:
        type: vertical-stack
        cards:
          - type: custom:mini-media-player
            entity: media_player.living_room_tv_universal
            group: false
            toggle_power: true
            name: Now Playing
            icon: mdi:television-classic
            scale: 1.2
            hide:
              name: false
              power: true
              controls: true
              volume: true
              mute: true
              icon_state: false
              runtime: false
              runtime_remaining: false
          - type: custom:expander-card
            title-card:
              type: markdown
              content: >
                {% from 'easy_time.jinja' import speak_the_days, clock_icon %}

                {% set next_game = state_attr('sensor.team_tracker',
                'date') %}


                {% set spoken_days = speak_the_days(as_datetime(next_game)) %}


                {% set game_state = states('sensor.team_tracker') %}


                {% set is_home = state_attr('sensor.team_tracker',
                'team_homeaway') ==

                "home" %}

                ## 🏀 {{state_attr('sensor.team_tracker', 'event_name')}}:
                {{ as_timestamp(next_game) | timestamp_custom('%A at %H:%M') }}
              style: |
                ha-card::before {
                  background-image: url("{{state_attr('sensor.team_tracker', 'league_logo')}}");
                  background-repeat: no-repeat, no-repeat;
                  background-size: 20%;
                  background-position: right;
                  background-origin: padding-box;
                  content: '';
                  filter: blur(0px) opacity(15%);
                  position: absolute;
                  inset: 0%;
                }
                ha-card {
                  background-origin: padding-box;
                  padding: 10px;
                  border: 0px !important;
                }
            cards:
              - type: custom:teamtracker-card
                entity: sensor.team_tracker
                home_side: right
            clear: false
            child-padding: "0"
          - type: grid
            cards:
              - type: picture-elements
                image: /local/images/white-background.svg
                elements:
                  - type: image
                    image: /local/images/jellyfin-logo.svg
                    style:
                      left: 47%
                      top: 47%
                      width: 94%
                      margin: 3% 3% 3% 3%
                    tap_action:
                      action: call-service
                      service: media_player.select_source
                      target:
                        device_id: 0123456789abcdef
                      data:
                        source: org.jellyfin.androidtv
              - type: picture-elements
                image: /local/images/white-background.svg
                elements:
                  - type: image
                    image: /local/images/youtube-logo.svg
                    style:
                      left: 47%
                      top: 47%
                      width: 94%
                      margin: 3% 3% 3% 3%
                    tap_action:
                      action: call-service
                      service: media_player.select_source
                      target:
                        device_id: 0123456789abcdef
                      data:
                        source: com.google.android.youtube.tv
              - type: picture-elements
                image: /local/images/white-background.svg
                elements:
                  - type: image
                    image: /local/images/netflix-logo.svg
                    style:
                      left: 47%
                      top: 47%                      width: 94%
                      margin: 3% 3% 3% 3%
                    tap_action:
                      action: call-service
                      service: media_player.select_source
                      target:
                        device_id: 0123456789abcdef
                      data:
                        source: com.netflix.ninja
              - type: picture-elements
                image: /local/images/white-background.svg
                elements:
                  - type: image
                    image: /local/images/max-logo.svg
                    style:
                      left: 47%
                      top: 47%
                      width: 94%
                      margin: 3% 3% 3% 3%
                    tap_action:
                      action: call-service
                      service: media_player.select_source
                      target:
                        device_id: 0123456789abcdef
                      data:
                        source: com.wbd.stream
              - type: picture-elements
                image: /local/images/white-background.svg
                elements:
                  - type: image
                    image: >-
                      /local/images/prime-video-logo.svg
                    style:
                      left: 47%
                      top: 47%
                      width: 94%
                      margin: 3% 3% 3% 3%
                    tap_action:
                      action: call-service
                      service: media_player.select_source
                      target:
                        device_id: 0123456789abcdef
                      data:
                        source: com.amazon.amazonvideo.livingroom
              - type: picture-elements
                image: /local/images/white-background.svg
                elements:
                  - type: image
                    image: /local/images/f1tv-logo.svg
                    style:
                      left: 47%
                      top: 47%
                      width: 94%
                      margin: 3% 3% 3% 3%
                    tap_action:
                      action: call-service
                      service: media_player.select_source
                      target:
                        device_id: 0123456789abcdef
                      data:
                        source: com.formulaone.production
              - type: picture-elements
                image: /local/images/white-background.svg
                elements:
                  - type: image
                    image: >-
                      /local/images/disney-plus-logo.svg
                    style:
                      left: 47%
                      top: 47%
                      width: 94%
                      margin: 3% 3% 3% 3%
                    tap_action:
                      action: call-service
                      service: media_player.select_source
                      target:
                        device_id: 0123456789abcdef
                      data:
                        source: com.disney.disneyplus
              - type: picture-elements
                image: /local/images/white-background.svg
                elements:
                  - type: image
                    image: /local/images/apple-tv-logo.svg
                    style:
                      left: 47%
                      top: 47%
                      width: 94%
                      margin: 3% 3% 3% 3%
                    tap_action:
                      action: call-service
                      service: media_player.select_source
                      target:
                        device_id: 0123456789abcdef
                      data:
                        source: com.apple.atve.androidtv.appletv
              - type: picture-elements
                image: /local/images/white-background.svg
                elements:
                  - type: image
                    image: >-
                      /local/images/paramount-plus-logo.svg
                    style:
                      left: 47%
                      top: 47%
                      width: 94%
                      margin: 3% 3% 3% 3%
                    tap_action:
                      action: call-service
                      service: media_player.select_source
                      target:
                        device_id: 0123456789abcdef
                      data:
                        source: com.cbs.ott
              - type: picture-elements
                image: /local/images/white-background.svg
                elements:
                  - type: image
                    image: /local/images/hulu-logo.svg
                    style:
                      left: 47%
                      top: 47%
                      width: 94%
                      margin: 3% 3% 3% 3%
                    tap_action:
                      action: call-service
                      service: media_player.select_source
                      target:
                        device_id: 0123456789abcdef
                      data:
                        source: com.hulu.livingroomplus
              - type: picture-elements
                image: /local/images/white-background.svg
                elements:
                  - type: image
                    image: >-
                      /local/images/youtube-music-logo.svg
                    style:
                      left: 47%
                      top: 47%
                      width: 94%
                      margin: 3% 3% 3% 3%
                    tap_action:
                      action: call-service
                      service: media_player.select_source
                      target:
                        device_id: 0123456789abcdef
                      data:
                        source: com.google.android.youtube.tvmusic
              - type: picture-elements
                image: /local/images/white-background.svg
                elements:
                  - type: image
                    image: /local/images/spotify-logo.svg
                    style:
                      left: 47%
                      top: 47%
                      width: 94%
                      margin: 3% 3% 3% 3%
                    tap_action:
                      action: call-service
                      service: media_player.select_source
                      target:
                        device_id: 0123456789abcdef
                      data:
                        source: com.spotify.tv.android
              - type: picture-elements
                image: /local/images/white-background.svg
                elements:
                  - type: image
                    image: >-
                      /local/images/play-store-logo.svg
                    style:
                      left: 42%
                      top: 42%
                      width: 84%
                      margin: 8% 8% 8% 8%
                    tap_action:
                      action: call-service
                      service: media_player.select_source
                      target:
                        device_id: 0123456789abcdef
                      data:
                        source: com.android.vending
              - type: picture-elements
                image: /local/images/white-background.svg
                elements:
                  - type: image
                    image: >-
                      /local/images/remote-locator-logo.svg
                    style:
                      left: 47%
                      top: 47%
                      width: 94%
                      margin: 3% 3% 3% 3%
                    tap_action:
                      action: call-service
                      service: script.living_room_tv_remote_locator
                      target: {}
              - type: picture-elements
                image: /local/images/white-background.svg
                elements:
                  - type: image
                    image: >-
                      /local/images/button-mapper-logo.webp
                    style:
                      left: 50%
                      top: 50%
                      width: 100%
                    tap_action:
                      action: call-service
                      service: media_player.select_source
                      target:
                        device_id: 0123456789abcdef
                      data:
                        source: flar2.homebutton
              - type: picture-elements
                image: /local/images/white-background.svg
                elements:
                  - type: image
                    image: /local/images/settings-logo.svg
                    style:
                      left: 47%
                      top: 47%
                      width: 94%
                      margin: 3% 3% 3% 3%
                    tap_action:
                      action: call-service
                      service: media_player.select_source
                      target:
                        device_id: 0123456789abcdef
                      data:
                        source: com.android.tv.settings
            columns: 4
      attributes:
        label: Media Sources
        icon: mdi:apps
```

`white-background.svg`
```svg
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1 1"><path d="M0,0h1v1H0z" fill="#FFF"/></svg>
```

`white-circle.svg`
```svg
<?xml version="1.0" standalone="yes"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="White Circle" viewbox="0 0 600 600" width="600" height="600">
	<circle id="white-circle" fill="#fff" cx="300" cy="300" r="300" />
</svg>
```

**Comment by leedomike** [comment]
I love this toggle to switch between touchpad and d-pad. Unfortunately, the program is way over my head. Anyway you can break it down for me?

**Reply by Nerwyn** [reply]
You can now use templating inline with the rows array to do this more clearly.

```yaml
type: custom:android-tv-card
rows:
  - |
    {% if is_state('input_boolean.living_room_tv_remote_d_pad_is_enabled', 'on') %}
      dpad
    {% else %}
      touchpad
    {% endif %}
```

You have to navigate to `Devices & services` > `Helpers` `+ CREATE HELPER` and create a `Toggle` helper to create the input boolean entity to use with this, or have it trigger on the state of something else.

**Reply by leedomike** [reply]
Thanks for that. This is all new for me, so still trying to figure everything out from scratch. I was able to figure out the helper to create the switch and used your code to be able to swap back and forth. However, how do I make the switch display directly on my remote? (re: the d-pad/touchpad switch directly below).

Thank you

**Reply by leedomike** [reply]
Okay, I think I figured it out. The coding is really over my head, but I was able to sift through it to get to the good stuff.

- I had to download a few custom cards via HACS because I didn't have them (i.e. lovelace-card-mod, stack-in-card, button-card, I think that's it).
- I realized what is going on is the OP is making individual cards, stacking them all into one card. With every indented card type being a new card.
- I combined your simplified code with OPs code to create the touchpad/d-pad + switch button (via helper script).
- Here is my basic code:
```
type: custom:stack-in-card
mode: vertical
cards:
  - type: custom:android-tv-card
    remote_id: remote.living_room_tv
    enable_button_feedback: true
    rows:
      - - >
          {% if is_state('input_boolean.living_room_tv_remote_d_pad_is_enabled',
          'on') %}
           dpad
          {% else %}
           touchpad
          {% endif %}
  - type: custom:mod-card
    style:
      hui-horizontal-stack-card$: |
        #root > button-card {
          margin: 0;
        }
    card:
      type: horizontal-stack
      cards:
        - type: custom:button-card
          entity: input_boolean.living_room_tv_remote_d_pad_is_enabled
          show_name: false
          color_type: card
          icon: mdi:gesture-tap-box
          styles:
            card:
              - height: 64px
              - border-radius: >-
                  var(--ha-card-border-radius,12px) 0px 0px
                  var(--ha-card-border-radius,12px)
              - border-color: >-
                  var(--state-inactive-color,
                  var(--state-input_boolean-off-color,
                  var(--state-disabled-color)))
              - border-width: 8px 0px 8px 8px
              - padding: 4px
          state:
            - value: 'on'
              styles:
                card:
                  - background-color: >-
                      var(--state-inactive-color,
                      var(--state-input_boolean-off-color,
                      var(--state-disabled-color)))
                icon:
                  - color: white
            - value: 'off'
              styles:
                card:
                  - background-color: >-
                      var(--switch-checked-button-color,
                      var(--state-input_boolean-on-color,
                      var(--state-active-color)))
                icon:
                  - color: black
          tap_action:
            action: call-service
            service: input_boolean.toggle
            data:
              entity_id: input_boolean.living_room_tv_remote_d_pad_is_enabled
        - type: custom:button-card
          entity: input_boolean.living_room_tv_remote_d_pad_is_enabled
          show_name: false
          icon: mdi:camera-control
          styles:
            card:
              - height: 64px
              - border-radius: >-
                  0px var(--ha-card-border-radius,12px)
                  var(--ha-card-border-radius,12px) 0px
              - border-color: >-
                  var(--state-inactive-color,
                  var(--state-input_boolean-off-color,
                  var(--state-disabled-color)))
              - border-width: 8px 8px 8px 0px
              - padding: 4px
          state:
            - value: 'on'
              styles:
                card:
                  - background-color: >-
                      var(--switch-checked-button-color,
                      var(--state-input_boolean-on-color,
                      var(--state-active-color)))
                icon:
                  - color: black
            - value: 'off'
              styles:
                card:
                  - background-color: >-
                      var(--state-inactive-color,
                      var(--state-input_boolean-off-color,
                      var(--state-disabled-color)))
                icon:
                  - color: white
          tap_action:
            action: call-service
            service: input_boolean.toggle
            data:
              entity_id: input_boolean.living_room_tv_remote_d_pad_is_enabled
```

Thanks for all the help!

**Reply by Nerwyn** [reply]
No problem! If you want to include the toggle for changing the navigation controls in the remote card directly, you can create a custom action for it and include it in the remote config like so:


```yaml
type: custom:android-tv-card
custom_actions:
  toggle_nav:
    icon: mdi:gesture-tap-box
    tap_action:
      action: call-service
      service: input_boolean.toggle
      data:
        entity_id: input_boolean.living_room_tv_remote_d_pad_is_enabled
rows:
  - |
    {% if is_state('input_boolean.living_room_tv_remote_d_pad_is_enabled', 'on') %}
      dpad
    {% else %}
      touchpad
    {% endif %}
  - - toggle_nav
```
