### ISSUE TITLE
Default `input` button

### ISSUE THREAD

**Issue by felipecrs** [Nerwyn/universal-remote-card#191]
**Is your feature request related to a problem? Please describe.**
Pretty much all TVs have an input button in their remote.

**Describe the solution you'd like**
It would be nice if a default input button was provided to simplify configuration.

**Describe alternatives you've considered**

```yaml
type: custom:universal-remote-card
rows:
  - - input
custom_actions:
  - type: button
    name: input
    icon: mdi:hdmi-port
```

**Additional context**
Icon suggestions are:

- https://pictogrammers.com/library/mdi/icon/hdmi-port/
- https://pictogrammers.com/library/mdi/icon/exit-to-app/ (same as from Chromecast with Google TV remote)
