### ISSUE TITLE
Better support for generic remotes

### ISSUE THREAD

**Issue by felipecrs** [Nerwyn/universal-remote-card#192]
**Is your feature request related to a problem? Please describe.**
It would be great if better support for generic remotes could be given. A good one to use as base is [Broadlink](https://www.home-assistant.io/integrations/broadlink/), lots of other integrations have implemented their remote entities based on it, like Tuya Local.

**Describe the solution you'd like**
A new _Generic_ remote platform. When the _Generic_ remote platform is selected, users can also set the _Device for Generic Remote_, and then all _Key_ actions targeting this remote will have their `device` populated by default.

```yaml
type: custom:universal-remote-card
platform: Generic
remote_id: remote.controle_remoto_do_quarto
generic_remote_device: sony_tv
rows:
  - - input
    - null
    - power
  - - volume_mute
    - volume_down
    - volume_up
custom_actions:
  - type: button
    name: input
    tap_action:
      action: key
      key: source
    icon: mdi:hdmi-port
  - type: button
    name: power
    tap_action:
      action: key
      key: on_off
    icon: mdi:power
  - type: button
    name: volume_mute
    tap_action:
      action: key
      key: mute
    icon: mdi:volume-low
  - type: button
    name: volume_down
    tap_action:
      action: key
      key: vol_down
    hold_action:
      action: repeat
    icon: mdi:volume-medium
  - type: button
    name: volume_up
    tap_action:
      action: key
      key: vol_up
    hold_action:
      action: repeat
    icon: mdi:volume-high
```

**Describe alternatives you've considered**
```yaml
type: custom:universal-remote-card
rows:
  - - input
    - null
    - power
  - - volume_mute
    - volume_down
    - volume_up
custom_actions:
  - type: button
    name: input
    tap_action:
      action: perform-action
      perform_action: remote.send_command
      target:
        entity_id: remote.controle_remoto_do_quarto
      data:
        device: sony_tv
        command: source
    icon: mdi:hdmi-port
  - type: button
    name: power
    tap_action:
      action: perform-action
      perform_action: remote.send_command
      target:
        entity_id: remote.controle_remoto_do_quarto
      data:
        device: sony_tv
        command: on_off
    icon: mdi:power
  - type: button
    name: volume_mute
    tap_action:
      action: perform-action
      perform_action: remote.send_command
      target:
        entity_id: remote.controle_remoto_do_quarto
      data:
        device: sony_tv
        command: mute
    icon: mdi:volume-low
  - type: button
    name: volume_down
    tap_action:
      action: perform-action
      perform_action: remote.send_command
      target:
        entity_id: remote.controle_remoto_do_quarto
      data:
        device: sony_tv
        command: vol_down
    hold_action:
      action: repeat
    icon: mdi:volume-medium
  - type: button
    name: volume_up
    tap_action:
      action: perform-action
      perform_action: remote.send_command
      target:
        entity_id: remote.controle_remoto_do_quarto
      data:
        device: sony_tv
        command: vol_up
    hold_action:
      action: repeat
    icon: mdi:volume-high
```

**Additional context**
N/A

**Comment by Nerwyn** [comment]
So a `Generic IR/RF` platform, that uses the `key` action as a shorthand for:

```yaml
action: perform-action
perform_action: remote.send_command
target:
  entity_id: {{ config.card.remote_id }}
data:
  device: {{ config.card.device }}
  command: {{ config.card.name }}
```

I'd also have to make `device` available when calling `key` as an action, and ensure that it autofills with the general config value if not provided.
