### ISSUE TITLE
Lots of errors since a few days "Uncaught error from Chrome WebView 135.0.7049.100 on Android"

### ISSUE THREAD

**Issue by Ices-Eyes** [Nerwyn/universal-remote-card#195]
**Checklist:**

- [v] I updated to the latest version available
- [v] I cleared the cache of my browser
- [v] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**
4.4.3
**Last working release (if known):**

**Browser and Operating System:**

**Description of problem:**
Got a bunch of this rows on home assistant log:
```
2025-04-28 12:23:55.660 ERROR (MainThread) [frontend.js.modern.202504110] Uncaught error from Chrome WebView 135.0.7049.100 on Android 12
Error: Failed to execute 'define' on 'CustomElementRegistry': the name "remote-button" has already been used with this registry
O.define (src/scoped-custom-element-registry.ts:180:12)
/hacsfiles/universal-remote-card/universal-remote-card.min.js:11:277661
y (/hacsfiles/universal-remote-card/universal-remote-card.min.js:11:324316)
/hacsfiles/universal-remote-card/universal-remote-card.min.js:11:328594
/hacsfiles/universal-remote-card/universal-remote-card.min.js:44:18471
/hacsfiles/universal-remote-card/universal-remote-card.min.js:44:18475
```

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Your Full Remote Config**

```yaml
type: custom:android-tv-card
rows:
  - - - - power
        - null
        - home
        - null
        - back
      - - volume_down
        - null
        - volume_mute
        - null
        - volume_up
      - - netflix
        - null
        - disney
        - null
        - primevideo
  - - - - n1
        - n2
        - n3
        - channel_up
      - - n4
        - n5
        - n6
        - channel_down
      - - n7
        - n8
        - n9
        - channel_previous
      - - info
        - n0
        - null
        - tv
  - dpad
custom_actions:
  - type: button
    name: power
    tap_action:
      action: toggle
      target:
        entity_id: media_player.samsung_q90
    icon: mdi:power
    styles: |-
      .icon {
        {% if is_state("media_player.samsung_q90", "on") %}
          color: #00FF00;
        {% else %}
          color: #FF0000;
        {% endif %}
      }
  - type: button
    name: netflix
    tap_action:
      action: source
      source: Netflix
    icon: mdi:netflix
    styles: |-
      :host {
        --icon-color: rgb(229, 9, 20);
      }
  - type: button
    name: disney
    tap_action:
      action: source
      source: Disney+
    icon: disney
    styles: |-
      :host {
        --icon-color: rgb(17, 60, 207);
      }
  - type: button
    name: primevideo
    tap_action:
      action: source
      source: Prime Video
    icon: primevideo
    styles: |-
      :host {
        --icon-color: rgb(0, 165, 222);
      }
  - type: button
    name: back
    tap_action:
      action: key
      key: KEY_RETURN
    icon: mdi:keyboard-backspace
    hold_action:
      action: key
      hold_time: 500
      key: KEY_EXIT
platform: Samsung TV
remote_id: remote.samsung_q90
media_player_id: media_player.samsung_q90
autofill_entity_id: true
haptics: false
grid_options:
  columns: full
```

**Additional information:**
