### ISSUE TITLE
Power, previous, and next buttons for LG WebOS TV

### ISSUE THREAD

**Issue by felipecrs** [Nerwyn/universal-remote-card#208]
They can be done like this:

```yaml
  - type: button
    name: power
    icon: mdi:power
    tap_action:
      action: perform-action
      perform_action: media_player.toggle
      target:
        entity_id: media_player.lg_webos_tv_uj7500
  - type: button
    name: previous
    icon: mdi:skip-previous
    tap_action:
      action: perform-action
      perform_action: media_player.media_previous_track
      target:
        entity_id: media_player.lg_webos_tv_uj7500
  - type: button
    name: next
    icon: mdi:skip-next
    tap_action:
      action: perform-action
      perform_action: media_player.media_next_track
      target:
        entity_id: media_player.lg_webos_tv_uj7500
```

Using the same `media_player_id`.

Too bad I didn't find a way to simulate the `source`/`input` button for WebOS. :(
