### ISSUE TITLE
Text elements? or a way too keep track of current volume

### ISSUE THREAD

**Issue by MahdiBM** [Nerwyn/universal-remote-card#212]
Currently it's hard to know what volume level the TV is on by just taking a look at the elements.
The best way i know is to have the volume slider which gives you an idea about what volume level you're on and when you change volume, but the number doesn't stick.

Generally i think it would be nice to be able to have a "text card" that can be customized with the volume number. That would be my preference, although i only have an immediate need for a volume-level indicator for now.

Other way might be to have the slider always show the level.

**Comment by MahdiBM** [comment]
For more context, this is my TV remote setup currently. I just added the slider to try it out, it's usually not there.

<kbd> <img width="457" alt="Image" src="https://github.com/user-attachments/assets/b75a1c17-876b-4a3f-bedb-c74dedc979c8" /> </kbd>

**Comment by MahdiBM** [comment]
Now that I've shared the cards, I should mention that by a "text card" i mean for example instead of the home button i could have a text that says "18" as the volume number, and that would be perfect.

**Comment by MahdiBM** [comment]
I guess having icons for numbers 11-100 would also be fine i. This case? Then I can put a template together to choose the correct number icon.

**Comment by Nerwyn** [comment]
All of the elements have a label field, which can be templated to show either the current element value or the state or attribute of another entity.

**Comment by Nerwyn** [comment]
[Example 9](https://github.com/Nerwyn/universal-remote-card?tab=readme-ov-file#example-9) uses a label within the slider to display current volume.

**Comment by MahdiBM** [comment]
Ok thank you, this looks great.
Settled on this for now:

Normally:

<kbd> <img width="510" alt="Image" src="https://github.com/user-attachments/assets/bb28974e-8f6b-499b-97f7-39f7b42658eb" /> </kbd>

When on mute/off:

<kbd> <img width="512" alt="Image" src="https://github.com/user-attachments/assets/ac81707b-c15e-49cc-9d20-7dcb7e130d06" /> </kbd>

```yaml
type: custom:universal-remote-card
remote_id: remote.bravia_4k_vh2
media_player_id: media_player.tv_bravia
rows:
  - - power
    - youtube
    - twitch
    - aaa
    - bbb
    - tv
  - - circlepad
  - - back
    - keyboard
    - volume_down
    - volume_up
    - volume_mute
    - home
custom_icons:
  - name: ""
custom_actions:
  - type: button
    name: twitch
    icon: mdi:twitch
    tap_action:
      action: perform-action
      perform_action: script.play_twitch
      target: {}
  - type: button
    name: aaa
    icon: mdi:television
    tap_action:
      action: perform-action
      perform_action: script.play_aaa
      target: {}
  - type: button
    name: bbb
    icon: mdi:movie-open-outline
    tap_action:
      action: perform-action
      perform_action: script.play_bbb
      target: {}
  - type: button
    name: settings
    tap_action:
      action: perform-action
      perform_action: remote.send_command
      target: {}
      data:
        num_repeats: 1
        delay_secs: 0.4
        hold_secs: 0
        command: Options
    icon: mdi:cog
    entity_id: remote.tv_bravia
  - type: button
    name: volume_mute
    tap_action:
      action: key
      key: MUTE
    icon: |
      {% if is_state_attr("media_player.bravia_4k_vh2", "volume_level", 0) %}
        mdi:volume-off
      {% elseif is_state_attr("media_player.bravia_4k_vh2", "volume_level", None) %}
        mdi:volume-off
      {% endif %}
    label: >
      {% if not is_state_attr("media_player.bravia_4k_vh2", "volume_level", 0)
      %}
        {{ int((float(state_attr("media_player.bravia_4k_vh2", "volume_level"), 0) *
      100)) }}  {% endif %}
    styles: |-
      :host {
        width: 48px;
      }
      .label {
        transform: var(--icon-transform);
        font-size: 30px;
        font-weight: 1000;
        color: var(--primary-text-color);
      }
    entity_id: media_player.bravia_4k_vh2
  - type: button
    name: volume_up
    tap_action:
      action: key
      key: VOLUME_UP
    hold_action:
      action: repeat
    icon: mdi:volume-plus
    entity_id: media_player.bravia_4k_vh2
  - type: button
    name: volume_down
    tap_action:
      action: key
      key: VOLUME_DOWN
    hold_action:
      action: repeat
    icon: mdi:volume-minus
    entity_id: media_player.bravia_4k_vh2
  - type: button
    name: password
    tap_action:
      action: perform-action
      perform_action: script.enter_password
      target: {}
    icon: mdi:form-textbox-password
    entity_id: remote.tv_bravia
  - type: button
    name: power
    tap_action:
      action: key
      remote_id: remote.tv_bravia
      key: TvPower
    icon: |
      {% if is_state("media_player.bravia_4k_vh2", "on") %}
        mdi:skull-outline
      {% else %}
        mdi:power
      {% endif %}
keyboard_id: media_player.tv_adb
platform: Android TV
```
