### ISSUE TITLE
Keyboard does not work on Sony Bravia w/ Google TV

### ISSUE THREAD

**Issue by MahdiBM** [Nerwyn/universal-remote-card#213]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [ ] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**
Current latest: 4.5.1

**Last working release (if known):**
None. I've only been using this integration (and generally HA) recently. Perhaps I started from 4.5.0.

**Browser and Operating System:**
Irrelevant in this case? macOS / Chromium / iPhone app / Android app

**Description of problem:**

The keyboard simply does not work. I have a lot of TV integrations and none seem to make things work.
The tv-related integrations are Google Cast, Android TV Remote, Android Debug Bridge, Sony Bravia TV.

<kbd> <img width="225" alt="Image" src="https://github.com/user-attachments/assets/8f71e0d6-dbda-4614-aec7-3157d9f8a1ac" /> </kbd>

The one integrations that _partially_ works is ADB. With that, there is a ton of delay when typing, and the main issue is that only numbers and dot and colon work (from first page of an Android phone keyboard), which means the normal keyboard letters don't work at all.

I also tried using unified_remote:
`unified_remote.yaml`:
```yaml
hosts:
  - host: tv_local_ip
    port: 5555
```
`5555` is the adb port number for Sony TV and does not change at all.

`configuration.yaml`:
```yaml
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

...

unified_remote: !include unified_remote.yaml

...
```

I have no issues typing on the TV with the Google TV app. Though I've noticed that app exclusively uses Bluetooth (at least in my case. Maybe there is something that makes it unable to connect through WiFi).

**Javascript errors shown in the web inspector (if applicable):**
n/a

**Your Full Remote Config**

This is my TV remote setup currently. I just added the slider to try it out, it's usually not there.

<kbd> <img width="457" alt="Image" src="https://github.com/user-attachments/assets/b75a1c17-876b-4a3f-bedb-c74dedc979c8" /> </kbd>

```yaml
type: custom:universal-remote-card
remote_id: remote.bravia_4k_vh2
media_player_id: media_player.tv_bravia
rows:
  - - power
    - youtube
    - twitch
    - aaa
    - bbb
    - tv
  - - circlepad
    - slider
  - - back
    - keyboard
    - volume_down
    - volume_up
    - volume_mute
    - home
custom_icons:
  - name: ""
custom_actions:
  - type: slider
    name: slider
    range:
      - 0
      - 1
    step: 0.01
    value_attribute: volume_level
    tap_action:
      action: perform-action
      perform_action: media_player.volume_set
      data:
        volume_level: "{{ value | float }}"
    vertical: true
    icon: mdi:volume-high
  - type: button
    name: twitch
    icon: mdi:twitch
    tap_action:
      action: perform-action
      perform_action: script.play_twitch
      target: {}
  - type: button
    name: aaa
    icon: mdi:television
    tap_action:
      action: perform-action
      perform_action: script.play_aaa
      target: {}
  - type: button
    name: bbb
    icon: mdi:movie-open-outline
    tap_action:
      action: perform-action
      perform_action: script.play_bbb
      target: {}
  - type: button
    name: settings
    tap_action:
      action: perform-action
      perform_action: remote.send_command
      target: {}
      data:
        num_repeats: 1
        delay_secs: 0.4
        hold_secs: 0
        command: Options
    icon: mdi:cog
    entity_id: remote.tv_bravia
  - type: button
    name: volume_mute
    tap_action:
      action: key
      key: MUTE
    icon: mdi:volume-off
    entity_id: media_player.bravia_4k_vh2
  - type: button
    name: volume_up
    tap_action:
      action: key
      key: VOLUME_UP
    hold_action:
      action: repeat
    icon: mdi:volume-plus
    entity_id: media_player.bravia_4k_vh2
  - type: button
    name: volume_down
    tap_action:
      action: key
      key: VOLUME_DOWN
    hold_action:
      action: repeat
    icon: mdi:volume-minus
    entity_id: media_player.bravia_4k_vh2
  - type: button
    name: password
    tap_action:
      action: perform-action
      perform_action: script.enter_password
      target: {}
    icon: mdi:form-textbox-password
    entity_id: remote.tv_bravia
  - type: button
    name: power
    tap_action:
      action: key
      remote_id: remote.tv_bravia
      key: TvPower
    icon: |
      {% if is_state("media_player.bravia_4k_vh2", "on") %}
        mdi:skull-outline
      {% else %}
        mdi:power
      {% endif %}
  - type: slider
    name: slider
    range:
      - 0
      - 1
    step: 0.01
    value_attribute: volume_level
    tap_action:
      action: perform-action
      perform_action: media_player.volume_set
      data:
        volume_level: "{{ value | float }}"
    vertical: true
    icon: mdi:volume-high
keyboard_id: media_player.tv_adb
platform: Android TV
```

**Additional information:**

I'm a developer as you can tell by my GitHub profile and I have the VSCode server installed. That's to say with a little bit of help i can try debug the problem so you can figure out what's wrong. I'm new to HA but still have a fine amount of understanding of it I'd think.

**Comment by Nerwyn** [comment]
The ADB keyboard is working fine for me and most users. You could try using Home Assistant's [action developer tool](http://homeassistant.local:8123/developer-tools/action) to send ADB text to your TV directly to see if the issue is there.

```yaml
action: remote.send_command
target:
  entity_id: remote.tv_adb
data:
  command: input text "This is a test"
```
