### ISSUE TITLE
Circlepad smaller center

### ISSUE THREAD

**Issue by MahdiBM** [Nerwyn/universal-remote-card#216]
This is not really a feature request but I only had the option to file it as a "bug report" or "feature request".
If there is a place on a Discord server or somewhere that would be a better place for asking questions, please let me know.

Thanks to this amazing repo (thanks to you 🙂) I've put together these cards below which are almost perfect to me (modulo the keyboard problem which I've filed, and I've yet to investigate more):

 <kbd> ![Image](https://github.com/user-attachments/assets/ee693428-3706-412f-bbf4-f687fbfad37b) </kbd>

What I want is for the Circlepad's center to become smaller. I want to make touching the direction buttons easier. I can accurately touch the center of my phone so it's not a problem for the circle to become smaller, but I can't say the same about the directions.

I'm not a frontend dev although I've put together some websites before and have a fine understanding of HTML/CSS/JS/Chrome-dev-tools. I wasn't sure how to go around finding out the answer myself. If there are any documents or something about home assistant or this repo specifically, I'll be happy to take a read so I can debug these stuff myself.

I know i'll need to have a custom `style`, in a custom Circlepad element, I just don't know what should be its contents.

What I currently have:

```yaml
type: custom:universal-remote-card
remote_id: remote.bravia_4k_vh2
media_player_id: media_player.tv_bravia
rows:
  - - power
    - youtube
    - twitch
    - aaa
    - bbb
    - tv
  - - - channel_1
      - channel_2
      - channel_3
      - channel_7
    - circlepad
    - - channel_6
      - channel_8
      - channel_4
      - channel_5
  - - back
    - password
    - volume_down
    - volume_up
    - volume_mute
    - home
custom_icons: null
custom_actions:
  - type: button
    name: twitch
    icon: mdi:twitch
    tap_action:
      action: perform-action
      perform_action: script.play_twitch
  - type: button
    name: aaa
    icon: mdi:television
    tap_action:
      action: perform-action
      perform_action: script.play_aaa
  - type: button
    name: bbb
    icon: mdi:movie-open-outline
    tap_action:
      action: perform-action
      perform_action: script.play_bbb
  - type: button
    name: settings
    tap_action:
      action: perform-action
      perform_action: remote.send_command
      data:
        command: Options
    icon: mdi:cog
    entity_id: remote.tv_bravia
  - type: button
    name: volume_mute
    tap_action:
      action: key
      key: MUTE
    icon: >
      {% if is_state_attr("media_player.bravia_4k_vh2", "volume_level", 0) %}
        mdi:volume-off
      {% elseif is_state_attr("media_player.bravia_4k_vh2", "volume_level",
      None) %}
        mdi:volume-off
      {% endif %}
    label: >
      {% if not is_state_attr("media_player.bravia_4k_vh2", "volume_level", 0)
      %}
        {{ int((float(state_attr("media_player.bravia_4k_vh2", "volume_level"), 0) *
      100)) }}  {% endif %}
    styles: |-
      :host {
        width: 48px;
        height: 48px;
      }
      .label {
        transform: var(--icon-transform);
        font-size: 30px;
        font-weight: 800;
        color: var(--primary-text-color);
      }
    entity_id: media_player.bravia_4k_vh2
  - type: button
    name: volume_up
    tap_action:
      action: key
      key: VOLUME_UP
    hold_action:
      action: repeat
    icon: mdi:volume-plus
    entity_id: media_player.bravia_4k_vh2
  - type: button
    name: volume_down
    tap_action:
      action: key
      key: VOLUME_DOWN
    hold_action:
      action: repeat
    icon: mdi:volume-minus
    entity_id: media_player.bravia_4k_vh2
  - type: button
    name: password
    tap_action:
      action: perform-action
      perform_action: script.enter_password
      target: {}
    icon: mdi:form-textbox-password
    entity_id: remote.tv_bravia
  - type: button
    name: power
    tap_action:
      action: key
      remote_id: remote.tv_bravia
      key: TvPower
    icon: |
      {% if is_state("media_player.bravia_4k_vh2", "on") %}
        mdi:skull-outline
      {% else %}
        mdi:power
      {% endif %}
  - type: button
    name: password
    entity_id: remote.bravia_4k_vh2
    icon: mdi:form-textbox-password
    tap_action:
      action: perform-action
      perform_action: script.enter_password
      target:
        entity_id: remote.bravia_4k_vh2
  - type: button
    name: channel_1
    icon: mdi:numeric-1-box
    entity_id: media_player.tv_bravia
    value_attribute: media_content_id
    tap_action:
      action: perform-action
      perform_action: script.play_a_channel
      data:
        channel: |
          {% if (value | int) == 26 %}
            1
          {% else %}
            26
          {% endif %}
  - type: button
    name: channel_2
    icon: mdi:numeric-2-box
    entity_id: media_player.tv_bravia
    value_attribute: media_content_id
    tap_action:
      action: perform-action
      perform_action: script.play_a_channel
      data:
        channel: |
          {% if (value | int) == 27 %}
            2
          {% else %}
            27
          {% endif %}
  - type: button
    name: channel_3
    icon: mdi:numeric-3-box
    entity_id: media_player.tv_bravia
    value_attribute: media_content_id
    tap_action:
      action: perform-action
      perform_action: script.play_a_channel
      data:
        channel: |
          {% if (value | int) == 28 %}
            3
          {% elif (value | int) == 3 %}
            41
          {% else %}
            28
          {% endif %}
  - type: button
    name: channel_4
    icon: mdi:tennis-ball
    entity_id: media_player.tv_bravia
    value_attribute: media_content_id
    tap_action:
      action: perform-action
      perform_action: script.play_a_channel
      data:
        channel: |
          {% if (value | int) == 29 %}
            17
          {% else %}
            29
          {% endif %}
  - type: button
    name: channel_5
    icon: mdi:newspaper-variant-outline
    entity_id: media_player.tv_bravia
    value_attribute: media_content_id
    tap_action:
      action: perform-action
      perform_action: script.play_a_channel
      data:
        channel: |
          {% if (value | int) == 31 %}
            6
          {% else %}
            31
          {% endif %}
  - type: button
    name: channel_6
    icon: mdi:alpha-n-box
    entity_id: media_player.tv_bravia
    value_attribute: media_content_id
    tap_action:
      action: perform-action
      perform_action: script.play_a_channel
      data:
        channel: |
          {% if (value | int) == 32 %}
            5
          {% else %}
            32
          {% endif %}
  - type: button
    name: channel_7
    icon: mdi:teddy-bear
    entity_id: media_player.tv_bravia
    value_attribute: media_content_id
    tap_action:
      action: perform-action
      perform_action: script.play_a_channel
      data:
        channel: |
          {% if (value | int) == 33 %}
            11
          {% else %}
            33
          {% endif %}
  - type: button
    name: channel_8
    icon: mdi:video-4k-box
    tap_action:
      action: perform-action
      perform_action: script.play_a_channel
      data:
        channel: 40
keyboard_id: media_player.tv_adb
platform: Android TV
```
