### ISSUE TITLE
BUG: Philips TV not available in list of platforms

### ISSUE THREAD

**Issue by tgechev** [Nerwyn/universal-remote-card#217]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser
- [x] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**
4.5.1

**Last working release (if known):**

**Browser and Operating System:**
Issue is present on Windows, Ubuntu and Android (Home Assistant Companion App). Tested with browsers Brave (Windows & Ubuntu), Microsoft Edge and Firefox (Ubuntu).

**Description of problem:**
`Philips TV` does not appear in the list of supported platforms even though it is listed as supported in the 4.5.1 release.

![Image](https://github.com/user-attachments/assets/e1908ba5-1893-4300-b09a-0adecc434f06)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Your Full Remote Config**

```
type: custom:android-tv-card
rows:
  - - power
    - youtube
    - kodi
  - - touchpad
  - - slider
  - - back
    - home
    - menu
  - - rewind
    - play_pause
    - fast_forward
  - - previous
    - stop
    - next
  - - info
  - - channel_up
    - guide
    - volume_up
  - - channel_down
    - volume_mute
    - volume_down
title: Philips TV Remote
remote_id: remote.tpm191e
media_player_id: media_player.50pus7304_12_2
grid_options:
  columns: 12
  rows: 8
custom_icons: []
```

**Additional information:**
I went in the integration's folder location `config\www\community\android-tv-card` and opened `universal-remote-card.min.js` with a text editor. I was able to search for (Ctrl+F) and find the platforms that are listed in the screenshot above, however, `Philips TV` was not found suggesting something went wrong with the latest build.
