### ISSUE TITLE
squished circlepad on iOS app

### ISSUE THREAD

**Issue by nick1802** [Nerwyn/universal-remote-card#225]
**Checklist:**

- [yes] I updated to the latest version available
- [yes] I cleared the cache of my browser
- [ ] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**
4.5.3
**Last working release (if known):**

**Browser and Operating System:**
iOS app

**Description of problem:**

with DPad after one of the HA updates the up/sown/left/right arrows moved but it remained circle
changed to circlepad. the outer circle is squished top and bottom. (on windows chrome broswer. everything looks like it should)
![Image](https://github.com/user-attachments/assets/696a3ced-efc4-4d6c-bc77-0a1add4a4da6)

**Your Full Remote Config**

```yaml
type: custom:universal-remote-card
rows:
  - - guide
    - null
    - null
    - null
    - null
    - null
    - null
    - info
  - - circlepad
  - - back
    - null
    - null
    - null
    - null
    - null
    - null
    - menu
custom_actions:
  - type: circlepad
    name: circlepad
    tap_action:
      action: key
      key: center
    up:
      icon: mdi:chevron-up
      tap_action:
        action: key
        key: up
      hold_action:
        action: repeat
    down:
      icon: mdi:chevron-down
      tap_action:
        action: key
        key: down
      hold_action:
        action: repeat
    left:
      icon: mdi:chevron-left
      tap_action:
        action: key
        key: left
      hold_action:
        action: repeat
    right:
      icon: mdi:chevron-right
      tap_action:
        action: key
        key: right
      hold_action:
        action: repeat
    styles: |-
      :host {
        width: 350px;      
      }

      #left,
      #right {
        width: 100%;
      }
  - type: button
    name: guide
    tap_action:
      action: perform-action
      perform_action: remote.send_command
      target:
        entity_id: remote.samsung_9_series_65
      data:
        num_repeats: 1
        delay_secs: 0.4
        hold_secs: 0
        command: KEY_GUIDE
    icon: mdi:television-guide
  - type: button
    name: info
    tap_action:
      action: perform-action
      perform_action: remote.send_command
      target:
        entity_id: remote.samsung_9_series_65
      data:
        num_repeats: 1
        delay_secs: 0.4
        hold_secs: 0
        command: KEY_INFO
    icon: mdi:information
  - type: button
    name: back
    tap_action:
      action: perform-action
      perform_action: remote.send_command
      target:
        entity_id: remote.samsung_9_series_65
      data:
        num_repeats: 1
        delay_secs: 0.4
        hold_secs: 0
        command: KEY_RETURN
    icon: mdi:arrow-left
  - type: button
    name: menu
    tap_action:
      action: perform-action
      perform_action: remote.send_command
      target:
        entity_id: remote.samsung_9_series_65
      data:
        num_repeats: 1
        delay_secs: 0.4
        hold_secs: 0
        command: KEY_HOME
    icon: mdi:menu
custom_icons: []
remote_id: remote.samsung_9_series_65


```

**Additional information:**
