### ISSUE TITLE
Elements tab is missing and Circlepad not visible

### ISSUE THREAD

**Issue by hafteto** [Nerwyn/universal-remote-card#228]
**Checklist:**

- [yes] I updated to the latest version available
- [yes] I cleared the cache of my browser
- [yes] I have confirmed that this is an issue with this project and not an integration by making the same actions with the [actions dev tool](http://homeassistant.local:8123/developer-tools/action)

**Release with the issue:**
Since circlepads are introduced
**Last working release (if known):**

**Browser and Operating System:**
Windows 11 with Chrome and Edge latest version browsers

**Description of problem:**
Elements tab is missing and Circlepad not visible

1. When is open edit on Universal Remote Card Elements tab is missing.

![Image](https://github.com/user-attachments/assets/74f0575b-811c-4ec6-b4f5-7ef615df0c5f)

2. Manual edit of the config, replacing dpad with circlepad, circlepads is not visible as buttons

![Image](https://github.com/user-attachments/assets/e5b851b1-a482-438d-86f2-5bdfb0070df6)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Your Full Remote Config**

```yaml

type: custom:android-tv-card
rows:
  - - power
    - home
    - settings
    - menu
    - back
  - circlepad
  - - play
    - pause
    - stop
    - rewind
    - fast_forward
  - - volume_up
    - volume_down
    - volume_mute
    - channel_up
    - channel_down
remote_id: remote.b_box_01
custom_actions: []
autofill_entity_id: true
haptics: true
keyboard_id: media_player.b_box_01_2
media_player_id: media_player.b_box_01_2
title: B-Box 01
custom_icons: []
grid_options:
  rows: auto
  columns: 12
visibility:
  - condition: state
    entity: input_boolean.b_box_remote
    state: "on"


```

**Additional information:**
